# Generated by Django 5.2.13 on 2026-06-29 10:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BollettaElettrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornitore', models.CharField(default='Acea', max_length=64, verbose_name='Fornitore')),
                ('pod', models.CharField(blank=True, max_length=20, verbose_name='POD')),
                ('periodo_inizio', models.DateField(verbose_name='Inizio periodo')),
                ('periodo_fine', models.DateField(verbose_name='Fine periodo')),
                ('importo_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Importo totale (€)')),
                ('kwh_fatturati', models.IntegerField(default=0, help_text='kWh di energia fatturati nel periodo della bolletta.', verbose_name='kWh fatturati')),
                ('prezzo_marginale_base', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='€/kWh sotto la soglia accisa (accisa = 0). Es. Acea: 0.193400', max_digits=10, verbose_name='Prezzo marginale base (€/kWh)')),
                ('accisa_marginale', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='€/kWh aggiuntivi sopra la soglia accisa. Es. Acea: 0.025000', max_digits=10, verbose_name='Accisa marginale (€/kWh)')),
                ('soglia_accisa_kwh', models.IntegerField(default=150, help_text="Soglia oltre cui scatta l'accisa marginale (3 kW residente: 150).", verbose_name='Soglia accisa (kWh/mese)')),
                ('sopra_soglia_accisa', models.BooleanField(default=False, help_text='True se kwh_fatturati supera la soglia accisa.', verbose_name='Sopra soglia accisa')),
                ('prezzo_marginale_medio', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Variabile A reale del mese: €/kWh marginale medio applicato.', max_digits=10, verbose_name='Prezzo marginale medio (€/kWh)')),
                ('prezzo_pubblicato_ha', models.DecimalField(blank=True, decimal_places=6, help_text='Valore effettivamente inviato a Home Assistant.', max_digits=10, null=True, verbose_name='Prezzo pubblicato in HA (€/kWh)')),
                ('ha_sync_at', models.DateTimeField(blank=True, help_text="Istante dell'ultima sync verso HA (riuscita o tentata).", null=True, verbose_name='Ultima sync HA')),
                ('ha_sync_ok', models.BooleanField(default=False, help_text="True se l'ultima pubblicazione in HA e andata a buon fine.", verbose_name='Sync HA riuscita')),
            ],
            options={
                'verbose_name': 'Bolletta elettrica',
                'verbose_name_plural': 'Bollette elettriche',
                'ordering': ['-periodo_fine'],
            },
        ),
        migrations.CreateModel(
            name='HaSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creato_il', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('modalita', models.CharField(choices=[('ultima_bolletta', 'Ultima bolletta'), ('media_mobile_12m', 'Media mobile 12 mesi'), ('manuale', 'Manuale / on-demand')], max_length=20, verbose_name='Modalità')),
                ('entity_id', models.CharField(blank=True, max_length=128, verbose_name='Entity HA')),
                ('valore', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Valore inviato (€/kWh)')),
                ('esito', models.BooleanField(default=False, verbose_name='Esito OK')),
                ('dettaglio_errore', models.TextField(blank=True, help_text='Messaggio diagnostico in caso di fallimento (senza segreti).', verbose_name='Dettaglio errore')),
                ('bolletta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ha_sync_logs', to='bollette.bollettaelettrica', verbose_name='Bolletta')),
            ],
            options={
                'verbose_name': 'Log sync HA',
                'verbose_name_plural': 'Log sync HA',
                'ordering': ['-creato_il'],
            },
        ),
    ]
