# Generated by Django 5.2.13 on 2026-09-25 22:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bollette', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BollettaGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornitore', models.CharField(default='Acea', max_length=64, verbose_name='Fornitore')),
                ('pdr', models.CharField(blank=True, max_length=20, verbose_name='PDR')),
                ('periodo_inizio', models.DateField(verbose_name='Inizio periodo')),
                ('periodo_fine', models.DateField(verbose_name='Fine periodo')),
                ('importo_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Importo totale (€)')),
                ('smc_fatturati', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Metri cubi standard fatturati nel periodo.', max_digits=10, verbose_name='Smc fatturati')),
                ('coeff_c', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Coefficiente di conversione volumetrico del contatore (es. 1.0272).', max_digits=8, verbose_name='Coefficiente C')),
                ('potere_calorifico_pcs', models.DecimalField(decimal_places=6, default=Decimal('0.038520'), help_text='Potere calorifico superiore convenzionale.', max_digits=8, verbose_name='PCS (GJ/Smc)')),
                ('quota_materia_prima_smc', models.DecimalField(decimal_places=6, default=Decimal('0.450000'), help_text='Prezzo base componente energia gas (€/Smc).', max_digits=10, verbose_name='Materia prima gas (€/Smc)')),
                ('quota_fissa_annua', models.DecimalField(decimal_places=2, default=Decimal('120.00'), help_text='Costi fissi commercializzazione e vendita (QVD).', max_digits=8, verbose_name='Quota fissa annua (€/anno)')),
                ('accisa_smc', models.DecimalField(decimal_places=6, default=Decimal('0.180000'), help_text='Imposte al consumo per Smc.', max_digits=10, verbose_name='Accisa e addizionale (€/Smc)')),
                ('prezzo_marginale_medio_smc', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Costo variabile marginale totale per Smc (materia + oneri var + accise).', max_digits=10, verbose_name='Prezzo marginale (€/Smc)')),
                ('gradi_giorno', models.DecimalField(blank=True, decimal_places=2, help_text='Gradi Giorno calcolati per il periodo da Open-Meteo.', max_digits=8, null=True, verbose_name='Gradi Giorno (HDD)')),
                ('temperatura_media', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temp. Media (°C)')),
                ('smc_per_gradi_giorno', models.DecimalField(blank=True, decimal_places=4, help_text='Indice di efficienza riscaldamento: Smc consumati per Grado Giorno.', max_digits=8, null=True, verbose_name='Smc / Gradi Giorno')),
                ('psv_medio_periodo', models.DecimalField(blank=True, decimal_places=6, help_text='Punto di Scambio Virtuale medio del periodo.', max_digits=10, null=True, verbose_name='PSV medio (€/Smc)')),
                ('spread_psv', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Spread vs PSV (€/Smc)')),
                ('prezzo_pubblicato_ha', models.DecimalField(blank=True, decimal_places=6, help_text='Valore €/Smc inviato a Home Assistant.', max_digits=10, null=True, verbose_name='Prezzo pubblicato in HA (€/Smc)')),
                ('ha_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Ultima sync HA')),
                ('ha_sync_ok', models.BooleanField(default=False, verbose_name='Sync HA riuscita')),
            ],
            options={
                'verbose_name': 'Bolletta gas',
                'verbose_name_plural': 'Bollette gas',
                'ordering': ['-periodo_fine'],
            },
        ),
        migrations.AddField(
            model_name='bollettaelettrica',
            name='gradi_giorno',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gradi Giorno riscaldamento calcolati da Open-Meteo per il periodo.', max_digits=8, null=True, verbose_name='Gradi Giorno (HDD)'),
        ),
        migrations.AddField(
            model_name='bollettaelettrica',
            name='kwh_per_gradi_giorno',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Indice di consumo normalizzato sul meteo.', max_digits=8, null=True, verbose_name='kWh / Gradi Giorno'),
        ),
        migrations.AddField(
            model_name='bollettaelettrica',
            name='pun_medio_periodo',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Prezzo Unico Nazionale medio nel periodo.', max_digits=10, null=True, verbose_name='PUN medio (€/kWh)'),
        ),
        migrations.AddField(
            model_name='bollettaelettrica',
            name='spread_pun',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Differenza tra prezzo marginale della bolletta e PUN.', max_digits=10, null=True, verbose_name='Spread vs PUN (€/kWh)'),
        ),
        migrations.AddField(
            model_name='bollettaelettrica',
            name='temperatura_media',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Temperatura media esterna registrata da Open-Meteo.', max_digits=5, null=True, verbose_name='Temp. Media (°C)'),
        ),
        migrations.AlterField(
            model_name='hasynclog',
            name='bolletta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ha_sync_logs', to='bollette.bollettaelettrica', verbose_name='Bolletta Elettrica'),
        ),
        migrations.AlterField(
            model_name='hasynclog',
            name='valore',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Valore inviato (€/kWh o €/Smc)'),
        ),
        migrations.AddField(
            model_name='hasynclog',
            name='bolletta_gas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ha_sync_logs', to='bollette.bollettagas', verbose_name='Bolletta Gas'),
        ),
    ]
