# Generated by Django 5.2.13 on 2026-09-26 07:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bollette', '0002_bollettagas_bollettaelettrica_gradi_giorno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurazioneSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ha_base_url', models.CharField(default='', help_text='Es. https://192.168.1.206:8123 (senza slash finale).', max_length=255, verbose_name='URL Base Home Assistant')),
                ('ha_token', models.TextField(blank=True, default='', help_text='Token di autenticazione generato nel profilo utente di Home Assistant.', verbose_name='Long-Lived Access Token HA')),
                ('ha_tls_verify', models.BooleanField(default=True, help_text='Disabilita se usi un certificato self-signed su IP locale senza CA custom.', verbose_name='Verifica certificato TLS')),
                ('ha_ca_bundle', models.CharField(blank=True, default='', help_text='Percorso al file .crt per validare certificati interni (opzionale).', max_length=255, verbose_name='Path CA Bundle / Certificato')),
                ('prezzo_ha_mode', models.CharField(choices=[('media_mobile_12m', 'Media mobile 12 mesi pesata'), ('ultima_bolletta', 'Ultima bolletta parsata')], default='media_mobile_12m', help_text='Come calcolare il prezzo inviato a Home Assistant.', max_length=32, verbose_name='Modalità calcolo prezzo HA')),
                ('ha_entity_kwh_consumo', models.CharField(blank=True, default='', help_text='Sensore cumulativo dei kWh per validazione (es. sensor.grid_consumption).', max_length=128, verbose_name='Entity consumi Luce (kWh)')),
                ('ha_entity_smc_consumo', models.CharField(blank=True, default='', help_text='Sensore dei consumi gas per validazione (es. sensor.gas_consumption).', max_length=128, verbose_name='Entity consumi Gas (Smc)')),
                ('ha_entity_prezzo_singolo', models.CharField(default='input_number.prezzo_energia_kwh', help_text='Helper HA in cui scrivere il costo marginale luce €/kWh.', max_length=128, verbose_name='Entity helper prezzo Luce')),
                ('ha_entity_prezzo_gas', models.CharField(default='input_number.prezzo_gas_smc', help_text='Helper HA in cui scrivere il costo marginale gas €/Smc.', max_length=128, verbose_name='Entity helper prezzo Gas')),
                ('ha_entity_pun', models.CharField(blank=True, default='sensor.pun_mono', help_text='Sensore PUN in HA (opzionale, es. da integrazione pun_sensor).', max_length=128, verbose_name='Entity sensore PUN in HA')),
                ('ha_sync_auto', models.BooleanField(default=False, help_text='Se attivo, pubblica subito il prezzo in HA appena viene creata una bolletta.', verbose_name='Sync automatica dopo ogni salvataggio')),
                ('meteo_citta', models.CharField(default='Roma', help_text="Città di riferimento per l'archivio meteo.", max_length=64, verbose_name='Nome Località')),
                ('meteo_latitude', models.DecimalField(decimal_places=4, default=Decimal('41.9028'), help_text='Latitudine geografica per le temperature storiche.', max_digits=8, verbose_name='Latitudine')),
                ('meteo_longitude', models.DecimalField(decimal_places=4, default=Decimal('12.4964'), help_text='Longitudine geografica.', max_digits=8, verbose_name='Longitudine')),
                ('ollama_base_url', models.CharField(default='http://127.0.0.1:11434', help_text='Indirizzo del server Ollama (es. http://192.168.1.X:11434 sul PC con RTX 5070 Ti).', max_length=255, verbose_name='URL Server Ollama')),
                ('ollama_model', models.CharField(default='qwen2.5:latest', help_text='Nome del modello scaricato in Ollama (es. qwen2.5:latest, llama3.2, ecc.).', max_length=64, verbose_name='Modello LLM Ollama')),
                ('aggiornato_il', models.DateTimeField(auto_now=True, verbose_name='Ultimo aggiornamento')),
            ],
            options={
                'verbose_name': 'Configurazione del Portale',
                'verbose_name_plural': 'Configurazione del Portale',
            },
        ),
        migrations.AddField(
            model_name='bollettaelettrica',
            name='data_emissione',
            field=models.DateField(blank=True, null=True, verbose_name='Data emissione fattura'),
        ),
        migrations.AddField(
            model_name='bollettaelettrica',
            name='file_bolletta',
            field=models.FileField(blank=True, help_text="PDF originale della bolletta conservato nell'archivio.", null=True, upload_to='bollette_pdf/luce/', verbose_name='File PDF bolletta'),
        ),
        migrations.AddField(
            model_name='bollettaelettrica',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note e osservazioni'),
        ),
        migrations.AddField(
            model_name='bollettaelettrica',
            name='numero_fattura',
            field=models.CharField(blank=True, max_length=64, verbose_name='Numero fattura'),
        ),
        migrations.AddField(
            model_name='bollettaelettrica',
            name='quota_fissa_mensile',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Costi fissi mensili di commercializzazione e vendita (CCV/PCV).', max_digits=8, verbose_name='Quota fissa mensile (€/mese)'),
        ),
        migrations.AddField(
            model_name='bollettagas',
            name='data_emissione',
            field=models.DateField(blank=True, null=True, verbose_name='Data emissione fattura'),
        ),
        migrations.AddField(
            model_name='bollettagas',
            name='file_bolletta',
            field=models.FileField(blank=True, help_text='PDF originale della bolletta gas archiviato.', null=True, upload_to='bollette_pdf/gas/', verbose_name='File PDF bolletta'),
        ),
        migrations.AddField(
            model_name='bollettagas',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note e osservazioni'),
        ),
        migrations.AddField(
            model_name='bollettagas',
            name='numero_fattura',
            field=models.CharField(blank=True, max_length=64, verbose_name='Numero fattura'),
        ),
    ]
