# Generated by Django 5.2.13 on 2026-09-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bollette', '0003_configurazionesistema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bollettaelettrica',
            name='fonte_misura_ha',
            field=models.CharField(blank=True, default='', help_text="Es: 'Polling REST API' o 'Import CSV'", max_length=64, verbose_name='Fonte misura HA'),
        ),
        migrations.AddField(
            model_name='bollettaelettrica',
            name='kwh_misurati_ha',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Consumo registrato dal contatore / sensore Home Assistant nel periodo.', max_digits=10, null=True, verbose_name='kWh misurati HA'),
        ),
        migrations.AddField(
            model_name='bollettaelettrica',
            name='scostamento_ha_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Differenza percentuale tra consumo fatturato e contatore HA.', max_digits=6, null=True, verbose_name='Scostamento HA (%)'),
        ),
        migrations.AddField(
            model_name='bollettagas',
            name='fonte_misura_ha',
            field=models.CharField(blank=True, default='', help_text="Es: 'Polling REST API' o 'Import CSV'", max_length=64, verbose_name='Fonte misura HA'),
        ),
        migrations.AddField(
            model_name='bollettagas',
            name='scostamento_ha_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Differenza percentuale tra consumo fatturato e sensore HA.', max_digits=6, null=True, verbose_name='Scostamento HA (%)'),
        ),
        migrations.AddField(
            model_name='bollettagas',
            name='smc_misurati_ha',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Consumo registrato dal sensore gas Home Assistant nel periodo.', max_digits=10, null=True, verbose_name='Smc misurati HA'),
        ),
    ]
