# Generated by Django 5.2.13 on 2026-10-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bollette', '0004_bollettaelettrica_fonte_misura_ha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetatmoRecordGiornaliero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, unique=True, verbose_name='Data')),
                ('secondi_caldaia', models.IntegerField(default=0, help_text='Secondi totali di accensione caldaia nel corso delle 24 ore.', verbose_name='Secondi accensione caldaia')),
                ('temp_interna_media', models.DecimalField(blank=True, decimal_places=2, help_text='Temperatura ambiente media registrata dalla sonda Netatmo.', max_digits=5, null=True, verbose_name='Temp. interna media (°C)')),
                ('temp_setpoint_media', models.DecimalField(blank=True, decimal_places=2, help_text='Temperatura impostata (target/setpoint) media.', max_digits=5, null=True, verbose_name='Temp. setpoint media (°C)')),
                ('n_campionamenti', models.IntegerField(default=0, help_text='Numero di rilevazioni aggregate per la giornata.', verbose_name='Numero campionamenti')),
                ('fonte_file', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome file origine')),
                ('creato_il', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('aggiornato_il', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
            ],
            options={
                'verbose_name': 'Record Giornaliero Netatmo',
                'verbose_name_plural': 'Record Giornalieri Netatmo',
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='bollettagas',
            name='costo_ora_caldaia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo medio per ogni ora di riscaldamento acceso (€/h).', max_digits=8, null=True, verbose_name='Costo orario caldaia (€/h)'),
        ),
        migrations.AddField(
            model_name='bollettagas',
            name='ore_caldaia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ore totali di accensione caldaia registrate da Netatmo nel periodo.', max_digits=8, null=True, verbose_name='Ore caldaia Netatmo'),
        ),
        migrations.AddField(
            model_name='bollettagas',
            name='smc_acs_cucina_stimati',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Smc stimati per acqua calda sanitaria e cucina (fabbisogno continuo).', max_digits=10, null=True, verbose_name='Smc ACS/Cucina stimati'),
        ),
        migrations.AddField(
            model_name='bollettagas',
            name='smc_ora_caldaia',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Consumo orario stimato del bruciatore (Smc per ora di fiamma).', max_digits=8, null=True, verbose_name='Smc / ora caldaia'),
        ),
        migrations.AddField(
            model_name='bollettagas',
            name='smc_riscaldamento_stimati',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Smc stimati per il riscaldamento dell'ambiente.", max_digits=10, null=True, verbose_name='Smc Riscaldamento stimati'),
        ),
        migrations.AddField(
            model_name='bollettagas',
            name='temp_interna_media',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Temperatura ambiente interna media registrata da Netatmo nel periodo.', max_digits=5, null=True, verbose_name='Temp. interna Netatmo (°C)'),
        ),
    ]
