# Generated by Django 5.2.13 on 2026-10-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bollette', '0005_netatmorecordgiornaliero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurazionesistema',
            name='netatmo_access_token',
            field=models.TextField(blank=True, default='', help_text='Token corrente rinnovato automaticamente via refresh token.', verbose_name='Access Token Netatmo (Cache)'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='netatmo_client_id',
            field=models.CharField(blank=True, default='', help_text="Ottenuto registrando un'app gratuita su dev.netatmo.com/apps.", max_length=128, verbose_name='Netatmo Client ID'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='netatmo_client_secret',
            field=models.CharField(blank=True, default='', help_text="Segreto API dell'applicazione Netatmo.", max_length=128, verbose_name='Netatmo Client Secret'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='netatmo_device_id',
            field=models.CharField(blank=True, default='', help_text='Indirizzo MAC del relè caldaia (rilevato in automatico via API).', max_length=64, verbose_name='MAC Relè Caldaia'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='netatmo_home_id',
            field=models.CharField(blank=True, default='', help_text="Identificativo dell'abitazione (rilevato in automatico via API).", max_length=64, verbose_name='ID Casa Netatmo'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='netatmo_module_id',
            field=models.CharField(blank=True, default='', help_text='Indirizzo MAC del termostato ambiente (rilevato in automatico via API).', max_length=64, verbose_name='ID Modulo Termostato'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='netatmo_refresh_token',
            field=models.TextField(blank=True, default='', help_text="Token OAuth2 ottenuto dal 'Token Generator' su dev.netatmo.com (scope: read_thermostat).", verbose_name='Netatmo Refresh Token'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='netatmo_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scadenza Access Token'),
        ),
    ]
