# Generated by Django 5.2.13 on 2026-10-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bollette', '0006_configurazionesistema_netatmo_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bollettaelettrica',
            name='canone_rai',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quota Canone RAI addebitata in bolletta.', max_digits=8, null=True, verbose_name='Canone abbonamento TV (€)'),
        ),
        migrations.AddField(
            model_name='bollettaelettrica',
            name='consumi_mensili',
            field=models.JSONField(blank=True, help_text="Lista di consumi mensili [{'inizio': 'YYYY-MM-DD', 'fine': 'YYYY-MM-DD', 'kwh': 123, 'tipo': 'Effettivo'|'Stimato'}].", null=True, verbose_name='Consumi mensili disaggregati'),
        ),
        migrations.AddField(
            model_name='bollettaelettrica',
            name='quota_fissa_netta_periodo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Somma netta di quota fissa vendita, rete e potenza del periodo (es. 39.90 €).', max_digits=8, null=True, verbose_name='Quota fissa netta periodo (€)'),
        ),
        migrations.AddField(
            model_name='bollettaelettrica',
            name='totale_da_pagare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Totale documento comprensivo di partite addizionali come Canone TV.', max_digits=10, null=True, verbose_name='Totale da pagare fattura (€)'),
        ),
    ]
