# Generated by Django 5.2.13 on 2026-10-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bollette', '0007_bollettaelettrica_canone_rai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurazionesistema',
            name='ha_base_url',
            field=models.CharField(default='', help_text='Es. https://homeassistant.local:8123 (senza slash finale).', max_length=255, verbose_name='URL Base Home Assistant'),
        ),
    ]
